name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
  run: npm install --legacy-peer-deps


      - name: Install Expo CLI
        run: npm install -g eas-cli

      - name: Build APK
        run: |
          eas build -p android --profile preview --non-interactive
